language: rust
dist: trusty
sudo: required
services:
  - docker

matrix:
  include:
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl

before_install: set -e

install:
  - sh .ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash .ci/build.sh

after_script: set +e

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

deploy:
  provider: script
  script: .ci/deploy.sh
  skip_cleanup: true
  on:
    tags: true
